steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy atualizar-status-pedido \
        --region=us-central1 \
        --runtime python311 \
        --trigger-http \
        --allow-unauthenticated \
        --source=. \
        --entry-point=aualizar_status_pedido
