steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud functions deploy listar-pedidos \
        --region=us-central1 \
        --runtime python312 \
        --trigger-http \
        --allow-unauthenticated \
        --source=. \
        --entry-point=listar_pedidos
